# -*- coding: utf-8 -*-
"""Canda_Capital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2NMDvmofFWeB05z5LeJJSljWw2Eqqow
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/AB_NYC_2019.csv")
df.head()

df.price.describe()

min_thresold, max_thresold = df.price.quantile([0.01,0.999])
min_thresold, max_thresold

df[df.price<min_thresold]

df2 = df[(df.price>min_thresold)&(df.price<max_thresold)]
df2.shape

df2.price.describe()